node{
	stage('SCM Checkout'){
		git 'https://github.com/hanumanad/webapp'
	}
	stage('Compile-Package'){
	def workspace = D:/maveen/webapp
         cd $workspace
	def mvnHome = tool name: 'maven-3.5.4', type: 'maven'
      sh "${mvnHome}/bin/mvn package"
        }
}
